### ISSUE TITLE
AWS access to different 'member accounts' within our Organisation

### ISSUE THREAD

**Issue by markhk67** [GreenerSoftware/IntroPage#4]
As an existing user in the kiehlmann AWS account
I want to be able to switch role and access any of the other GreenerSoftware accounts,
So that I can do so without the need for an additional IAM User credentials (like I set up with david.carboni)

https://personalmhk.atlassian.net/wiki/spaces/MK/pages/1362034690/Establish+remote+access+to+other+AWS+accounts+with+additional+IAM+User+credentials

https://www.youtube.com/watch?v=BfE2G-fsBNU

**Comment by markhk67** [comment]
The AWS documentation to support this is below:
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_accounts_access.html

NB By default the "Switch Role" OrganizationAccountAccessRole is only availabe for 1 hour...

- NS_AlwaysOn_Acc: 637423416545 - success
- OrganizationalAccountAccessRole: “OrgAccAccessRole_NS_AlwaysOn”
- 
- NS_TimeBound_Acc: 851725449784 - success
- OrganizationalAccountAccessRole: “OrganizationAccountAccessRole”
- 
- NS_FullyResponsive_Acc: 471112586809 - success
- OrganizationalAccountAccessRole: “OrganizationAccountAccessRole”



![image](https://github.com/GreenerSoftware/IntroPage/assets/144790603/ce11b876-ed0d-45d0-83fd-b887d7df9539)


![image](https://github.com/GreenerSoftware/IntroPage/assets/144790603/94910c41-fb31-40bd-9eeb-aa1502c050d1)

![image](https://github.com/GreenerSoftware/IntroPage/assets/144790603/0aa60639-9775-4579-93d1-1f268d46c484)

**Comment by davidcarboni** [comment]
To switch role in the cli, you can set up a profile.

StackOverflow answer: https://serverfault.com/a/933083/130018

Example:

```
[kiehlmann]
aws_access_key_id = AK.............
aws_secret_access_key = xxxxxxxxxxxxxxxxxxx
[alwayson]
role_arn = arn:aws:iam::637423416545:role/OrgAccAccessRole_NS_AlwaysOn 
source_profile = kiehlmann
[timebound]
role_arn = arn:aws:iam::851725449784:role/OrganizationAccountAccessRole
source_profile = kiehlmann
[fullyresponsive]
role_arn = arn:aws:iam::471112586809:role/OrganizationAccountAccessRole
source_profile = kiehlmann
```

You then set an `AWS_PROFILE` environment variable to switch between roles.

NB Account ID for the Sandbox account is `058264171014` if you need that too.

**Comment by markhk67** [comment]
successful for David and Rory.

**Comment by davidcarboni** [comment]
Adding a note on how to share an AMI with the different accounts: 

Docs: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-explicit.html

Edit AMI Premissions screen: https://eu-west-2.console.aws.amazon.com/ec2/home?region=eu-west-2#EditImagePermissions:imageId=ami-0afdfebe7e1952d3e
